### PR TITLE
Add markdown format and gitbook info

### PR DESCRIPTION
**Pull request by jim3ma**

### CODE REVIEW

**Comment by dmbaturin** [comment]
Hey, sorry for late reply! My most important question is, how that file is supposed to be used? ;)

Also, however it's used, I believe it would be better to add a script for generating it automatically since the document will keep expanding.

**Comment by jim3ma** [comment]
https://jim3ma.github.io/books/iproute2-cheatsheet/index.html

I think gitbook style is better for reading. And we can also generate epub or other format for kindlle and so on

**Comment by dmbaturin** [comment]
@jim3ma I know of gitbook. My question is, what is the procedure that you used to create the page in question?
My concern is that gitbook.com itself is a proprietary, free trial service, and introducing a dependency on proprietary tools is a very bad practice for open source projects.
I assume you used https://github.com/GitbookIO/gitbook , which is abandoned and not even mentioned by gitbook on their website. Are there actively maintained forks?

**Comment by dmbaturin** [comment]
gitbook CLI is now officially deprecated, which means this can't be built without a proprietary service.

**Pull request closed without merging**
